name: 'PR Title Emoji'
description: 'Add emojis to conventional commit PR titles'
inputs:
  github_token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'